version: '3.1'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo


  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '8069:8069'
    environment:
      PG_HOST: postgres
      PG_USER: odoo
      PG_PASSWORD: odoo
      LONGPOLLING_PORT: 8072
      WORKERS: 3
      PORT: 8069

volumes:
  postgres:
